name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
  merge_group:

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build contentlayer
        run: pnpm build:contentlayer

      - name: Run lint
        run: pnpm lint
        env:
          SKIP_ENV_VALIDATION: true

      - name: Run type-check
        run: pnpm type-check
        env:
          SKIP_ENV_VALIDATION: true
